// Generated by gencpp from file framework/IntStrRequest.msg
// DO NOT EDIT!


#ifndef FRAMEWORK_MESSAGE_INTSTRREQUEST_H
#define FRAMEWORK_MESSAGE_INTSTRREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace framework
{
template <class ContainerAllocator>
struct IntStrRequest_
{
  typedef IntStrRequest_<ContainerAllocator> Type;

  IntStrRequest_()
    : ID(0)
    , data()  {
    }
  IntStrRequest_(const ContainerAllocator& _alloc)
    : ID(0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _ID_type;
  _ID_type ID;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::framework::IntStrRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::framework::IntStrRequest_<ContainerAllocator> const> ConstPtr;

}; // struct IntStrRequest_

typedef ::framework::IntStrRequest_<std::allocator<void> > IntStrRequest;

typedef boost::shared_ptr< ::framework::IntStrRequest > IntStrRequestPtr;
typedef boost::shared_ptr< ::framework::IntStrRequest const> IntStrRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::framework::IntStrRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::framework::IntStrRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace framework

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::framework::IntStrRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::framework::IntStrRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::framework::IntStrRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::framework::IntStrRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::framework::IntStrRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::framework::IntStrRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::framework::IntStrRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ed77e519248baadab08f3e394e3241b0";
  }

  static const char* value(const ::framework::IntStrRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xed77e519248baadaULL;
  static const uint64_t static_value2 = 0xb08f3e394e3241b0ULL;
};

template<class ContainerAllocator>
struct DataType< ::framework::IntStrRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "framework/IntStrRequest";
  }

  static const char* value(const ::framework::IntStrRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::framework::IntStrRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 ID\n"
"string data\n"
;
  }

  static const char* value(const ::framework::IntStrRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::framework::IntStrRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ID);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IntStrRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::framework::IntStrRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::framework::IntStrRequest_<ContainerAllocator>& v)
  {
    s << indent << "ID: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ID);
    s << indent << "data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FRAMEWORK_MESSAGE_INTSTRREQUEST_H
