# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rdt_localization/Limb_Vector.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Limb_Vector(genpy.Message):
  _md5sum = "95198abd0938eea51c580fdd9748821b"
  _type = "rdt_localization/Limb_Vector"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool door
int64 linActs_speed
int64 arm_speed
int64 drum_speed"""
  __slots__ = ['door','linActs_speed','arm_speed','drum_speed']
  _slot_types = ['bool','int64','int64','int64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       door,linActs_speed,arm_speed,drum_speed

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Limb_Vector, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.door is None:
        self.door = False
      if self.linActs_speed is None:
        self.linActs_speed = 0
      if self.arm_speed is None:
        self.arm_speed = 0
      if self.drum_speed is None:
        self.drum_speed = 0
    else:
      self.door = False
      self.linActs_speed = 0
      self.arm_speed = 0
      self.drum_speed = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B3q().pack(_x.door, _x.linActs_speed, _x.arm_speed, _x.drum_speed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 25
      (_x.door, _x.linActs_speed, _x.arm_speed, _x.drum_speed,) = _get_struct_B3q().unpack(str[start:end])
      self.door = bool(self.door)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B3q().pack(_x.door, _x.linActs_speed, _x.arm_speed, _x.drum_speed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 25
      (_x.door, _x.linActs_speed, _x.arm_speed, _x.drum_speed,) = _get_struct_B3q().unpack(str[start:end])
      self.door = bool(self.door)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B3q = None
def _get_struct_B3q():
    global _struct_B3q
    if _struct_B3q is None:
        _struct_B3q = struct.Struct("<B3q")
    return _struct_B3q
