// Generated by gencpp from file rdt_localization/Obstacle.msg
// DO NOT EDIT!


#ifndef RDT_LOCALIZATION_MESSAGE_OBSTACLE_H
#define RDT_LOCALIZATION_MESSAGE_OBSTACLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rdt_localization
{
template <class ContainerAllocator>
struct Obstacle_
{
  typedef Obstacle_<ContainerAllocator> Type;

  Obstacle_()
    : left(false)
    , right(false)  {
    }
  Obstacle_(const ContainerAllocator& _alloc)
    : left(false)
    , right(false)  {
  (void)_alloc;
    }



   typedef uint8_t _left_type;
  _left_type left;

   typedef uint8_t _right_type;
  _right_type right;





  typedef boost::shared_ptr< ::rdt_localization::Obstacle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rdt_localization::Obstacle_<ContainerAllocator> const> ConstPtr;

}; // struct Obstacle_

typedef ::rdt_localization::Obstacle_<std::allocator<void> > Obstacle;

typedef boost::shared_ptr< ::rdt_localization::Obstacle > ObstaclePtr;
typedef boost::shared_ptr< ::rdt_localization::Obstacle const> ObstacleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rdt_localization::Obstacle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rdt_localization::Obstacle_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rdt_localization::Obstacle_<ContainerAllocator1> & lhs, const ::rdt_localization::Obstacle_<ContainerAllocator2> & rhs)
{
  return lhs.left == rhs.left &&
    lhs.right == rhs.right;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rdt_localization::Obstacle_<ContainerAllocator1> & lhs, const ::rdt_localization::Obstacle_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rdt_localization

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rdt_localization::Obstacle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rdt_localization::Obstacle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rdt_localization::Obstacle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rdt_localization::Obstacle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rdt_localization::Obstacle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rdt_localization::Obstacle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rdt_localization::Obstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0544cac0b98e92509d14f758d50cf24b";
  }

  static const char* value(const ::rdt_localization::Obstacle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0544cac0b98e9250ULL;
  static const uint64_t static_value2 = 0x9d14f758d50cf24bULL;
};

template<class ContainerAllocator>
struct DataType< ::rdt_localization::Obstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rdt_localization/Obstacle";
  }

  static const char* value(const ::rdt_localization::Obstacle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rdt_localization::Obstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool left\n"
"bool right\n"
;
  }

  static const char* value(const ::rdt_localization::Obstacle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rdt_localization::Obstacle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left);
      stream.next(m.right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Obstacle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rdt_localization::Obstacle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rdt_localization::Obstacle_<ContainerAllocator>& v)
  {
    s << indent << "left: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RDT_LOCALIZATION_MESSAGE_OBSTACLE_H
