// Generated by gencpp from file rdt_localization/Pose.msg
// DO NOT EDIT!


#ifndef RDT_LOCALIZATION_MESSAGE_POSE_H
#define RDT_LOCALIZATION_MESSAGE_POSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rdt_localization
{
template <class ContainerAllocator>
struct Pose_
{
  typedef Pose_<ContainerAllocator> Type;

  Pose_()
    : x(0.0)
    , y(0.0)
    , orientation(0.0)  {
    }
  Pose_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , orientation(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _orientation_type;
  _orientation_type orientation;





  typedef boost::shared_ptr< ::rdt_localization::Pose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rdt_localization::Pose_<ContainerAllocator> const> ConstPtr;

}; // struct Pose_

typedef ::rdt_localization::Pose_<std::allocator<void> > Pose;

typedef boost::shared_ptr< ::rdt_localization::Pose > PosePtr;
typedef boost::shared_ptr< ::rdt_localization::Pose const> PoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rdt_localization::Pose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rdt_localization::Pose_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rdt_localization

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'rdt_localization': ['/home/dan/Code/RMC20/nuc_code/src/rdt_localization/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rdt_localization::Pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rdt_localization::Pose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rdt_localization::Pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rdt_localization::Pose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rdt_localization::Pose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rdt_localization::Pose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rdt_localization::Pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1c567beaed44a5d11b818be4c87fec7b";
  }

  static const char* value(const ::rdt_localization::Pose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1c567beaed44a5d1ULL;
  static const uint64_t static_value2 = 0x1b818be4c87fec7bULL;
};

template<class ContainerAllocator>
struct DataType< ::rdt_localization::Pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rdt_localization/Pose";
  }

  static const char* value(const ::rdt_localization::Pose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rdt_localization::Pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 orientation\n"
;
  }

  static const char* value(const ::rdt_localization::Pose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rdt_localization::Pose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.orientation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Pose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rdt_localization::Pose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rdt_localization::Pose_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "orientation: ";
    Printer<float>::stream(s, indent + "  ", v.orientation);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RDT_LOCALIZATION_MESSAGE_POSE_H
